//
//  Scenarios.swift
//  HeroRosterApp
//
//  Created by Craig Carlson on 11/30/15.
//  Copyright © 2015 Craig Carlson. All rights reserved.
//

import Foundation


struct Scenarios {
    let indexTitles = ["0","1", "2", "3", "4", "5", "6", "7", "M", "S"]
    let seasons = ["Season 0", "Season 1", "Season 2", "Season 3", "Season 4", "Season 5", "Season 6", "Season 7", "Modules", "Specials"]
    let scenarioNames = [["1 Silent Tide",
        "2 The Hydras Fang Incident",
        "3 Murder on the Silken Caravan",
        "4 The Frozen Fingers of Midnight",
        "5 Mists of Mwangi",
        "6 Black Waters",
        "7 Among the Living",
        "8 Slave Pits of Absalom",
        "9 Eye of the Crocodile King (RETIRED)",
        "10 Blood at Dralkard Manor (RETIRED)",
        "11 The Third Riddle (RETIRED)",
        "12 Stay of Execution (RETIRED)",
        "13 The Prince of Augustana",
        "14 The Many Fortunes of Grandmaster Torch",
        "15 The Asmodeus Mirage (RETIRED)",
        "16 To Scale the Dragon",
        "17 Perils of the Pirate Pact",
        "18 The Trouble with Secrets (RETIRED)",
        "19 Skeleton Moon (RETIRED)",
        "20 King Xeros of Old Azlant",
        "21 The Eternal Obelisk (RETIRED)",
        "22 Fingerprints of the Fiend",
        "23 Tide of Morning",
        "24 Decline of Glory",
        "25 Hands of the Muted God (RETIRED)",
        "26 Lost at Bitter End",
        "27 Our Lady of Silver",
        "28 Lyrics of Extinction"],
        
        ["29 The Devil We Know Part I: Shipyard Rats",
            "30 The Devil We Know Part II: Cassomir’s Locker",
            "31 Sniper in the Deep",
            "32 Drow of the Darklands Pyramid",
            "33 Assault on the Kingdom of the Impossible",
            "34 Encounter at the Drowning Stones",
            "35 Voice in the Void",
            "36 Echoes of the Everwar Part I: The Prisoner of Skull Hill",
            "37 The Beggar’s Pearl",
            "38 No Plunder No Pay",
            "39 The Citadel of Flame",
            "40 Hall of Drunken Heroes",
            "41 The Devil We Know Part III: Crypt of Fools",
            "42 Echoes of the Everwar Part II: The Watcher of Ages",
            "43 The Pallid Plague",
            "44 Echoes of the Everwar Part III: Terror at Whistledown",
            "45 Delirium’s Tangle",
            "46 Eyes of the Ten Part I: Requiem for the Red Raven",
            "47 The Darkest Vengeance",
            "48 The Devil We Know Part IV: Rules of the Swift",
            "49 Among the Dead",
            "50 Fortune’s Blight",
            "51 The City of Strangers Part I: The Shadow Gambit",
            "52 The City of Strangers Part II: The Twofold Demise",
            "53 Echoes of the Everwar Part IV: The Faithless Dead",
            "54 Eyes of the Ten Part II: The Maze of the Open Road",
            "55 The Infernal Vault",
            "56 The Jester’s Fraud"],
        
        ["2-01 Before the Dawn Part I: The Bloodcove Disguise",
            "2-02 Before the Dawn Part II: Rescue at Azlant Ridge",
            "2-03 The Rebel’s Ransom",
            "2-04 Shadows Fall on Absalom",
            "2-05 Eyes of the Ten Part III: Red Revolution",
            "2-06 The Heresy of Man Part I: The First Heresy",
            "2-07 The Heresy of Man Part II: Where Dark Things Sleep",
            "2-08 The Sarkorian Prophecy",
            "2-09 The Heresy of Man Part III: Beneath Forgotten Sands",
            "2-10 Fury of the Fiend",
            "2-11 The Penumbral Accords",
            "2-12 Below the Silver Tarn",
            "2-13 Murder on the Throaty Mermaid",
            "2-14 The Chasm of Screams",
            "2-15 Shades of Ice Part I: Written in Blood",
            "2-16 The Flesh Collector",
            "2-17 Shades of Ice Part II: Exiles of Winter",
            "2-18 The Forbidden Furnace of Forgotten Koor",
            "2-19 Shades of Ice Part III: Keep of the Huscarl King",
            "2-20 Wrath of the Accursed",
            "2-21 The Dalsine Affair",
            "2-22 Eyes of the Ten Part IV, Nothing Ventured Nothing Gained",
            "2-23 Shadow’s Last Stand Part I: At Shadow’s Door",
            "2-24 Shadow’s Last Stand Part II: Web of Corruption",
            "2-25 You Only Die Twice",
            "2-26 The Mantis’s Prey"],
        
        ["Intro 1: First Steps Part I: In Service to Lore",
            "Intro 2: First Steps Part II: To Delve the Dungeon Deep (RETIRED)",
            "Intro 3: First Steps Part III: A Vision of Betrayal (RETIRED)",
            "3-01 The Frostfur Captives",
            "3-02 Sewer Dragons of Absalom",
            "3-03 The Ghenett Manor Gauntlet",
            "3-04 The Kortos Envoy",
            "3-05 Tide of Twilight",
            "3-06 Song of the Sea Witch",
            "3-07 Echoes of the Overwatched",
            "3-08 Among the Gods",
            "3-09 The Quest for Perfection Part I: The Edge of Heaven",
            "3-10 The Immortal Conundrum",
            "3-11 The Quest for Perfection Part II: On Hostile Waters",
            "3-12 Wonders in the Weave Part I: The Dog Pharaoh’s Tomb",
            "3-13 The Quest for Perfection Part III: Defenders of Nesting Swallow",
            "3-14 Wonders in the Weave Part II: Snakes in the Fold",
            "3-15 The Haunting of Hinojai",
            "3-16 The Midnight Mauler",
            "3-17 Red Harvest",
            "3-18 The God’s Market Gamble",
            "3-19 The Icebound Outpost",
            "3-20 The Rats of Round Mtn Part I: Sundered Path",
            "3-21 The Temple of Empyreal Enlightenment",
            "3-22 The Rats of Round Mtn Part II: Pagoda of the Rat",
            "3-23 The Goblinblood Dead",
            "3-24 The Golden Serpent",
            "3-25 Storming the Diamond Gate",
            "3-26 Portal of the Sacred Rune"],
        
        ["4-01 Rise of the Goblin Guild",
            "4-02 In Wrath’s Shadow",
            "4-03 The Golemworks Incident",
            "4-04 King of the Storval Stairs",
            "4-05 The Sanos Abduction",
            "4-06 The Green Market",
            "4-07 Severing Ties",
            "4-08 The Cultist’s Kiss",
            "4-09 The Blakros Matrimony",
            "4-10 Feast of Sigils",
            "4-11 The Disappeared",
            "4-12 The Refuge of Time",
            "4-13 Fortress of the Nail",
            "4-14 My Enemy’s Enemy",
            "4-15 The Cyphermage Dilemma",
            "4-16 The Fabric of Reality",
            "4-17 Tower of the Ironwood Watch",
            "4-18 The Veteran’s Vault",
            "4-19 The Night March of Kalkamedes",
            "4-20 Words of the Ancients",
            "4-21 Way of the Kirin",
            "4-22 Glories of the Past Part I: Halls of Dwarven Lore",
            "4-23 Rivalry’s End",
            "4-24 Glories of the Past Part II: The Price of Friendship",
            "4-25 Glories of the Past Part III: The Secrets Stones Keep",
            "4-26 The Waking Rune",
            "4-EX Day of the Demon"],
        
        ["5-01 The Glass River Rescue",
            "5-02 The Wardstone Patrol",
            "5-03 The Hellknight’s Feast",
            "5-04 The Stolen Heir",
            "5-05 The Elven Entanglement",
            "5-06 You Have What You Hold",
            "5-07 Port Godless",
            "5-08 The Confirmation",
            "5-09 The Traitor’s Lodge",
            "5-10 Where Mammoths Dare Not Tread",
            "5-11 Library of the Lion",
            "5-12 Destiny of the Sand Part 1: A Bitter Bargain",
            "5-13 Weapon in the Rift",
            "5-14 Day of the Demon",
            "5-15 Destiny of the Sands Part 2: Race to Seeker’s Folly",
            "5-16 Destiny of the Sands Part 3: Sanctum of the Sages",
            "5-17 Fate of the Fiend",
            "5-18 The Stranger Within",
            "5-19 The Horn of Aroden",
            "5-20 The Sealed Gate",
            "5-21 The Merchant’s Wake",
            "5-22 Scars of the Third Crusade",
            "5-23 Cairn of Shadows",
            "5-24 Assault on the Wound",
            "5-25 Vengeance at Sundered Crag",
            "5-99 The Paths We Choose"],
        
        ["6-01 Trial by Machine",
            "6-02 The Silver Mount Collection",
            "6-03 The Technic Siege",
            "6-04 The Beacon Below",
            "6-05 Slave Ships of Absalom",
            "6-06 Hall of the Flesh Eaters",
            "6-07 Valley of Veiled Flame",
            "6-08 The Segang Expedition",
            "6-09 By Way of Bloodcove",
            "6-10 The Wounded Wisp",
            "6-11 The Slave Master’s Mirror",
            "6-12 Scions of the Sky Key Part 1: On Sharrowsmith’s Trail",
            "6-13 Of Kirin and Kraken",
            "6-14 Scions of the Sky Key Part 2: Kaava Quarry",
            "6-15 The Overflow Archives",
            "6-16 Scions of the Sky Key Part 3: The Golden Guardian",
            "6-17 Fires of Karamoss",
            "6-18 From Under Ice",
            "6-19 Test of Tar Kuata",
            "6-20 Returned to the Sky",
            "6-21 Tapestry’s Toil",
            "6-22 Out of Anarchy",
            "6-23 The Darkest Abduction"],
        
        ["7-01 Between the Lines",
            "7-02 Six Seconds to Midnight",
            "7-03 The Bronze House Reprisal",
            "7-04 The Ironbound Schism",
            "7-05 School of Spirits",
            "7-06 To Judge a Soul Part 1: The Lost Legacy",
            "7-07 Trouble in Tamran",
            "7-08 To Judge a Soul Part 2: Karma Reclaimed",
            "7-09 The Blakros Connection",
            "7-10 The Consortium Connection",
            "7-11 Ancients’ Anguish",
            "7-12 The Twisted Circle",
            "7-13 Captive in Crystal",
            "7-14 Let Bygones Be",
            "7-15 The Deepmarket Deception",
            "7-16 Lost Colony of Taldor",
            "7-17 Thralls of the Shattered God",
            "7-18 The Infernal Inheritance",
            "7-19",
            "7-20",
            "7-21",
            "7-22",
            "7-23"],
        
        ["Academy of Secrets",
            "Broken Chains",
            "Carrion Hill",
            "City of Golden Death",
            "Crypt of the Everflame",
            "Cult of the Ebon Destroyers",
            "Curse of the Riven Sky",
            "Dawn of the Scarlet Sun",
            "Doom Comes to Dustpawn",
            "The Dragon’s Demand",
            "Fangwood Keep",
            "Feast of Ravenmoor",
            "From Shore to Sea",
            "The Godsmouth Heresy",
            "The Harrowing",
            "Masks of the Living God",
            "Master of the Fallen Fortress",
            "The Midnight Mirror",
            "The Moonscar",
            "Murder’s Mark",
            "No Response from Deepmar",
            "Plunder and Peril",
            "Realm of the Fellnight Queen",
            "Risen from the Sands",
            "The Ruby Phoenix Tournament",
            "Tears at Bitter Manor",
            "Tomb of the Iron Medusa",
            "We Be Goblins!",
            "We Be Goblins Too!",
            "We Be Goblins Free!",
            "The Witchwar Legacy",
            "Thornkeep – The Accursed Halls",
            "Thornkeep – The Forgotten Laboratory",
            "Thornkeep – The Enigma Vaults",
            "Thornkeep – The Dark Menagerie",
            "Thornkeep – Sanctum of a Lost Age",
            "The Emerald Spire – Level 1 The Tower Ruins",
            "The Emerald Spire – Level 2 The Cellars",
            "The Emerald Spire – Level 3 Splinterden",
            "The Emerald Spire – Level 4 Godhome",
            "The Emerald Spire – Level 5 The Drowned Level",
            "The Emerald Spire – Level 6 The Clockwork Maze",
            "The Emerald Spire – Level 7 Shrine of the Awakener",
            "The Emerald Spire – Level 8 The Circle of Vissk-Thar",
            "The Emerald Spire – Level 9 The Spire Axis",
            "The Emerald Spire – Level 10 The Magma Vault",
            "The Emerald Spire – Level 11 The Tomb of Yarrix",
            "The Emerald Spire – Level 12 The Automaton Forge",
            "The Emerald Spire – Level 13 The Pleasure Gardens",
            "The Emerald Spire – Level 14 The Throne of Azlant",
            "The Emerald Spire – Level 15 Order and Chaos",
            "The Emerald Spire – Level 16 The Emerald Root"],
        
        ["2010 – Year of the Shadow Lodge",
            "2011 – Blood Under Absalom",
            "2012 – Race for the Runecarved Key",
            "2013 – Siege of the Diamond City",
            "2014 6-00 – Legacy of the Stonelords",
            "2015 7-00 – The Sky Key Solution",
            "6-97 – Siege of Serpents",
            "6-98 – Serpents Rise",
            "6-99 – True Dragons of Absalom",
            "Ruins of Bonekeep-Level One – The Silent Grave",
            "Ruins of Bonekeep-Level Two – Maze to the Mind Slave",
            "Grand Melee PaizoCon 2011",
            "Grand Convocation PaizoCon 2012"]]
}